services:
  bootc-desktop:
    build:
      context: .
      dockerfile: Containerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-quay.io/hummingbird-community/bootc-os:latest}
        ENABLE_FEDORA_RAWHIDE_REPO: ${ENABLE_FEDORA_RAWHIDE_REPO:-0}
        COPR_REPO: ${COPR_REPO:-}
        COPR_CHROOT: ${COPR_CHROOT:-}
    image: ${IMAGE_NAME:-localhost/bootc-desktop:latest}
